---
version: 2.1

orbs:
  terraform: twdps/terraform@0.1.0

# ==== global pipeline parameters

parameters:
  terraform-version:
    description: terraform version for all jobs
    type: string
    default: "1.0.6"
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team

# ==== triggers

# git push: deploy nonprod (dps-2)
on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

# git tag: deploy prod (dps-1)
on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      env:
        type: string
        default: ''
    steps:
      - run:
          name: set ~/.terraformrc
          command: secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
      - run:
          name: set << parameters.env >> environment variables
          command: secrethub inject -i environments/<< parameters.env >>.auto.tfvars.json.tpl -o << parameters.env >>.auto.tfvars.json
      - run:
          name: set twdps.io gpg keys
          command: bash scripts/import_gpg_keys.sh

jobs:

  test-configuration-and-write-credentials:
    description: |
      bats tests of the resulting infrastructure resources and write the service accounts
      credentials when successful during create_iam_profiles run.
    docker:
      - image: twdps/circleci-infra-aws:alpine-1.0.0
    shell: secrethub run -- /bin/sh -eo pipefail
    parameters:
      env:
        type: string
        default: ''
    steps:
      - checkout
      - setup_remote_docker
      - set-environment:
          env: << parameters.env >>
      - run:
          name: test << parameters.env >> configuration
          command: bash scripts/test_configuration.sh << parameters.env >>
      - when:
          condition:
            equal: [ << parameters.env >>, "nonprod" ]
          steps:
            - run:
                name: write service account credentials when create_iam_profiles = true
                command: bash scripts/write_service_account_credentials.sh

workflows:
  version: 2
  lab-iam-profiles-pipeline:

    jobs:
      - terraform/plan:
          name: nonprod-change-plan
          context: << pipeline.parameters.context >>
          shell: secrethub run --env-file secrethub.nonprod.env -- /bin/sh -eo pipefail
          workspace: nonprod
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                env: nonprod
          filters: *on-push-main

      - approve-nonprod-changes:
          type: approval
          requires:
            - nonprod-change-plan
          filters: *on-push-main

      - terraform/apply:
          name: nonprod-change-apply
          context: << pipeline.parameters.context >>
          shell: secrethub run --env-file secrethub.nonprod.env -- /bin/sh -eo pipefail
          workspace: nonprod
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                env: nonprod
          requires:
            - approve-nonprod-changes
          filters: *on-push-main

      - test-configuration-and-write-credentials:
          name: test-nonprod-iam-configuration
          context: << pipeline.parameters.context >>
          env: nonprod
          requires:
            - nonprod-change-apply
          filters: *on-push-main

      # release
      - terraform/plan:
          name: prod-change-plan
          context: << pipeline.parameters.context >>
          shell: secrethub run --env-file secrethub.prod.env -- /bin/sh -eo pipefail
          workspace: prod
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                env: prod
          filters: *on-tag-main

      - approve-prod-changes:
          type: approval
          requires:
            - prod-change-plan
          filters: *on-tag-main

      - terraform/apply:
          name: prod-change-apply
          context: << pipeline.parameters.context >>
          shell: secrethub run --env-file secrethub.prod.env -- /bin/sh -eo pipefail
          workspace: prod
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                env: prod
          requires:
            - approve-prod-changes
          filters: *on-tag-main
    
      - test-configuration-and-write-credentials:
          name: test-prod-iam-configuration
          context: << pipeline.parameters.context >>
          env: prod
          requires:
            - prod-change-apply
          filters: *on-tag-main
