---
version: 2.1

orbs:
  terraform: feedyard/terraform@0.1.0

# git push: plan, release, test nonprod account changes
on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

# git tag: plan, release, test prod account changes
on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2
  lab-iam-profiles-pipeline:

    jobs:
      - terraform/plan:
          name: nonprod-change-plan
          context: ZTW
          shell: secrethub run --env-file secrethub.nonprod.env -- /bin/sh -eo pipefail
          workspace: nonprod
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  cp tpl/iam_profiles.tf.tpl iam_profiles.tf
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/nonprod.auto.tfvars.json.tpl -o nonprod.auto.tfvars.json
          filters: *on-push-master

      - approve-nonprod-changes:
          type: approval
          requires:
            - nonprod-change-plan
          filters: *on-push-master

      - terraform/apply:
          name: nonprod-change-apply
          context: ZTW
          shell: secrethub run --env-file secrethub.nonprod.env -- /bin/sh -eo pipefail
          workspace: nonprod
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  cp tpl/iam_profiles.tf.tpl iam_profiles.tf
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/nonprod.auto.tfvars.json.tpl -o nonprod.auto.tfvars.json
                  secrethub inject -i tpl/public.key.tpl -o .public.key
                  secrethub inject -i tpl/private.key.tpl -o .private.key
                  secrethub inject -i tpl/import_gpg_keys.sh.tpl -o import_gpg_keys.sh
                  secrethub inject -i tpl/write_service_account_credentials.sh.tpl -o write_service_account_credentials.sh
                  bash import_gpg_keys.sh
          after-terraform:
            - run:
                name: test nonprod account changes
                command: secrethub run --env-file secrethub.nonprod.env -- bats test
            - run:
                name: write service account credentials
                command: bash write_service_account_credentials.sh
          requires:
            - approve-nonprod-changes
          filters: *on-push-master

      - terraform/plan:
          name: prod-change-plan
          context: ZTW
          shell: secrethub run --env-file secrethub.prod.env -- /bin/sh -eo pipefail
          workspace: prod
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/prod.auto.tfvars.json.tpl -o prod.auto.tfvars.json
          filters: *on-tag-master

      - approve-prod-changes:
          type: approval
          requires:
            - prod-change-plan
          filters: *on-tag-master

      - terraform/apply:
          name: prod-change-apply
          context: ZTW
          shell: secrethub run --env-file secrethub.prod.env -- /bin/sh -eo pipefail
          workspace: nonprod
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/prod.auto.tfvars.json.tpl -o prod.auto.tfvars.json
          after-terraform:
            - run:
                name: test prod account changes
                command: secrethub run --env-file secrethub.prod.env -- bats test/lab-iam-roles.bats
          requires:
            - approve-prod-changes
          filters: *on-tag-master
