---
version: 2.1

orbs:
  terraform: feedyard/terraform@0.6.0

# git push: deploy nonprod (dps-2)
on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

# git tag: deploy prod (dps-1)
on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      env:
        type: string
        default: ''
    steps:
      - run:
          name: set ~/.terraformrc
          command: secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
      - run:
          name: set << parameters.env >> environment variables
          command: secrethub inject -i environments/<< parameters.env >>.auto.tfvars.json.tpl -o << parameters.env >>.auto.tfvars.json
      - run:
          name: set twdps.io gpg keys
          command: bash scripts/import_gpg_keys.sh

  test-configuration-and-write-credentials:
    description: |
      bats tests of the resulting infrastructure resources and write the service accounts
      credentials when successful during create_iam_profiles run.
    parameters:
      env:
        type: string
        default: ''
    steps:
      - run:
          name: test << parameters.env >> configuration
          command: bash scripts/test_configuration.sh << parameters.env >>
      - when:
          condition:
            equal: [ << parameters.env >>, "nonprod" ]
          steps:
            - run:
                name: write service account credentials when create_iam_profiles = true
                command: bash scripts/write_service_account_credentials.sh

workflows:
  version: 2
  lab-iam-profiles-pipeline:

    jobs:
      - terraform/plan:
          name: nonprod-change-plan
          context: twdps-core-labs-team
          shell: secrethub run --env-file secrethub.nonprod.env -- /bin/sh -eo pipefail
          workspace: nonprod
          before-terraform:
            - set-environment:
                env: nonprod
          filters: *on-push-master

      - approve-nonprod-changes:
          type: approval
          requires:
            - nonprod-change-plan
          filters: *on-push-master

      - terraform/apply:
          name: nonprod-change-apply
          context: twdps-core-labs-team
          shell: secrethub run --env-file secrethub.nonprod.env -- /bin/sh -eo pipefail
          workspace: nonprod
          before-terraform:
            - set-environment:
                env: nonprod
          after-terraform:
            - test-configuration-and-write-credentials:
                env: nonprod
          requires:
            - approve-nonprod-changes
          filters: *on-push-master

      # release
      - terraform/plan:
          name: prod-change-plan
          context: twdps-core-labs-team
          shell: secrethub run --env-file secrethub.prod.env -- /bin/sh -eo pipefail
          workspace: prod
          before-terraform:
            - set-environment:
                env: prod
          filters: *on-tag-master

      - approve-prod-changes:
          type: approval
          requires:
            - prod-change-plan
          filters: *on-tag-master

      - terraform/apply:
          name: prod-change-apply
          context: twdps-core-labs-team
          shell: secrethub run --env-file secrethub.prod.env -- /bin/sh -eo pipefail
          workspace: prod
          before-terraform:
            - set-environment:
                env: prod
          after-terraform:
            - test-configuration-and-write-credentials:
                env: prod
          requires:
            - approve-prod-changes
          filters: *on-tag-master
