---
version: 2.1

orbs:
  terraform: feedyard/terraform@dev:latest

on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2
  lab-iam-profiles-pipeline:

    jobs:
      # git push = plan master-profile and nonprod-role changes
      - terraform/plan:
          name: master-change-plan
          context: ZTW
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: master
          before-terraform:
            - run:
                name: setup app.terraform.io credentials from secrets
                command: secrethub inject -i terraformrc.tpl -o ~/.terraformrc
            - run:
                name: setup auto.tfvars from secrets
                command: secrethub inject -i master.auto.tfvars.json.tpl -o master.auto.tfvars.json

      - terraform/plan:
          name: nonprod-change-plan
          context: ZTW
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: nonprod
          working-directory: roles
          var-file: accounts/nonprod.json
          before-terraform:
            - run:
                name: setup app.terraform.io credentials from secrets
                command: secrethub inject -i terraformrc.tpl -o ~/.terraformrc

      - approve-master-and-nonprod-changes:
          type: approval
          requires:
            - master-change-plan
            - nonprod-change-plan

      - terraform/apply:
          context: ZTW
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: master
          before-terraform:
            - run:
                name: setup credentials from secrets
                command: |
                  secrethub inject -i terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i master.auto.tfvars.json.tpl -o master.auto.tfvars.json
                  secrethub inject -i public.key.tpl -o .public.key
                  secrethub inject -i private.key.tpl -o .private.key
                  secrethub inject -i import_gpg_keys.sh.tpl -o import_gpg_keys.sh
                  secrethub inject -i write_service_account_credentials.sh.tpl -o write_service_account_credentials.sh
                  bash import_gpg_keys.sh
          after-terraform:
            - run:
                name: test master account changes
                command: secrethub run -- bats test
            - run:
                name: write service account credentials
                command: bash write_service_account_credentials.sh
          requires:
            - approve-master-and-nonprod-changes
