---
version: 2.1

orbs:
  terraform: feedyard/terraform@dev:latest

on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2
  lab-iam-profiles-pipeline:
    jobs:
      - terraform/plan:
          context: ZTW
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: nonprod
          var-file: accounts/nonprod.json
          before-terraform:
            - run:
                name: setup app.terraform.io credentials from secrets
                command: secrethub inject -i terraformrc.tpl -o ~/.terraformrc
            - run:
                name: setup tfvars from secrets
                command: secrethub inject -i master.auto.tfvars.json.tpl -o master.auto.tfvars.json

